language: ruby
cache: bundler

rvm:
  - 2.3.1

services:
  - docker

addons:
  apt:
    packages:
    - libpq-dev
    - libmagickcore-dev
    - libmagickwand-dev
install:
  - gem install bundler
  - bundle install
script:
  - docker build . -t dreams
  - bundle exec rspec spec -fd
notifications:
  email: false

