defaults: &defaults
  available_roles:
    - manager
    - vp
    - qa
    - liquidation
    - cfo
    - construction
    - foreman
    - pyromaniac
    - designer
  new_roles:
    - mooper

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
